# Generated by Django 2.2 on 2019-05-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=36)),
                ('data_validade', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_utilizacao', models.DateTimeField(blank=True, null=True)),
                ('utilizado', models.BooleanField(verbose_name=False)),
                ('ativo', models.BooleanField(verbose_name=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_criados', to='tablet.Pessoa')),
            ],
        ),
    ]
