# Generated by Django 2.2 on 2019-05-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusuario',
            name='chave',
            field=models.UUIDField(),
        ),
    ]
