# Generated by Django 2.2 on 2019-05-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet', '0002_auto_20190509_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusuario',
            name='chave',
            field=models.CharField(max_length=36),
        ),
    ]
