# Generated by Django 2.2 on 2019-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet', '0003_auto_20190509_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='senha_temporaria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
